name: Security Tests

on:
  pull_request:
    branches:
      - '*'

permissions:
  checks: write
  contents: read
  id-token: write

jobs:
  security-tests:
    runs-on: ubuntu-latest
    env:
      BRIGHT_HOSTNAME: development.playground.brightsec.com
      BRIGHT_PROJECT_ID: nKXKC76rXmrwttMt6c9gjP
      BRIGHT_TARGET_URL: http://127.0.0.1:9000
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: Install Go dependencies
        run: go mod download

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Install SecTester dependencies
        run: npm i --save=false --prefix .brightsec @sectester/core @sectester/repeater @sectester/scan @sectester/runner @sectester/reporter

      - name: Start application
        run: go run main.go &

      - name: Wait for application to be ready
        run: |
          for i in {1..10}; do
            nc -zv 127.0.0.1 9000 && echo "Application is ready" && exit 0
            echo "Waiting for application..."
            sleep 5
          done
          echo "Application did not start in time" && exit 1

      - name: Authenticate with Bright
        uses: ./.github/workflows/composite/configure-bright-credentials
        with:
          BRIGHT_HOSTNAME: ${{ env.BRIGHT_HOSTNAME }}
          BRIGHT_PROJECT_ID: ${{ env.BRIGHT_PROJECT_ID }}
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}

      - name: Run security tests
        env:
          BRIGHT_TOKEN: ${{ secrets.BRIGHT_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          node --experimental-transform-types --experimental-strip-types --experimental-detect-module \
          --disable-warning=MODULE_TYPELESS_PACKAGE_JSON --disable-warning=ExperimentalWarning \
          --test-force-exit --test .brightsec/tests/*.test.ts --test-concurrency=4
